package view;

import javax.swing.JFrame;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;
import org.jfree.data.time.SimpleTimePeriod;

import control.ControlPlannable;
import control.Utils;
import entity.WorkBreakDownElement;

/**
 * This code was edited or generated using CloudGarden's Jigloo SWT/Swing GUI
 * Builder, which is free for non-commercial use. If Jigloo is being used
 * commercially (ie, by a corporation, company or business for any purpose
 * whatever) then you should purchase a license for each developer using Jigloo.
 * Please visit www.cloudgarden.com for details. Use of Jigloo implies
 * acceptance of these licensing terms. A COMMERCIAL LICENSE HAS NOT BEEN
 * PURCHASED FOR THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED LEGALLY FOR
 * ANY CORPORATE OR COMMERCIAL PURPOSE.
 */
public class ViewPlannable extends javax.swing.JPanel {
	/*
	 * ViewPlannable.java
	 * 
	 * Created on 26 janvier 2006, 03:05
	 */

	private ControlPlannable plannableC;

	
	
	/** Creates new form PlannableView */
    public ViewPlannable(ControlPlannable p) 
    {
    	plannableC = p;
        initComponents();
        updateDaysChart();
        updateWorkChart();
        updateTextFields();
    }
	
	
	
//	 Variables declaration - do not modify
    private javax.swing.JPanel workChartPanel;
    private javax.swing.JButton bResUsg;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel daysChartPanel;
    private javax.swing.JPanel durationOffsetPanel;
    private javax.swing.JPanel durationPanel;
    private javax.swing.JPanel endDatesPanel;
    private javax.swing.JPanel endOffsetPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel startDatesPanel;
    private javax.swing.JPanel startOffsetPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtDurationOffset;
    private javax.swing.JTextField txtDurationOffset2;
    private javax.swing.JTextField txtGlobalOffset;
    private javax.swing.JTextField txtGlobalOffset2;
    private javax.swing.JTextField txtPrevDuration;
    private javax.swing.JTextField txtPrevEndDate;
    private javax.swing.JTextField txtPrevStartDate;
    private javax.swing.JTextField txtPrevWorkAmount;
    private javax.swing.JTextField txtRealDuration;
    private javax.swing.JTextField txtRealEndDate;
    private javax.swing.JTextField txtRealStartDate;
    private javax.swing.JTextField txtRealWorkAmount;
    private javax.swing.JTextField txtStartOffset;
    private javax.swing.JTextField txtStartOffset2;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JPanel workPanel;
    // End of variables declaration
	
    
    
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        startDatesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrevStartDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRealStartDate = new javax.swing.JTextField();
        endDatesPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPrevEndDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRealEndDate = new javax.swing.JTextField();
        durationPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtPrevDuration = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRealDuration = new javax.swing.JTextField();
        startOffsetPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtStartOffset = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtStartOffset2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        endOffsetPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtGlobalOffset = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtGlobalOffset2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        durationOffsetPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtDurationOffset = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtDurationOffset2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        daysChartPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        workPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtPrevWorkAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRealWorkAmount = new javax.swing.JTextField();
        workChartPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        bResUsg = new javax.swing.JButton();

        
        jPanel1.setLayout(new java.awt.BorderLayout(2, 5));

        titlePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titlePanel.add(txtTitle);

        jPanel1.add(titlePanel, java.awt.BorderLayout.NORTH);

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));

        startDatesPanel.setLayout(new java.awt.GridLayout(1, 4, 2, 2));

        startDatesPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        startDatesPanel.setMinimumSize(new java.awt.Dimension(400, 20));
        startDatesPanel.setPreferredSize(new java.awt.Dimension(400, 20));
        jLabel1.setText("Date d\u00e9but pr\u00e9visionnelle");
        startDatesPanel.add(jLabel1);

        txtPrevStartDate.setEditable(false);
        txtPrevStartDate.setPreferredSize(new java.awt.Dimension(100, 20));
        startDatesPanel.add(txtPrevStartDate);

        jLabel4.setText("Date d\u00e9but r\u00e9elle");
        startDatesPanel.add(jLabel4);

        txtRealStartDate.setEditable(false);
        txtRealStartDate.setPreferredSize(new java.awt.Dimension(100, 20));
        
        startDatesPanel.add(txtRealStartDate);

        contentPanel.add(startDatesPanel);

        endDatesPanel.setLayout(new java.awt.GridLayout(1, 4, 2, 2));

        endDatesPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        endDatesPanel.setMinimumSize(new java.awt.Dimension(400, 20));
        endDatesPanel.setPreferredSize(new java.awt.Dimension(400, 20));
        jLabel2.setText("Date fin pr\u00e9visionnelle");
        endDatesPanel.add(jLabel2);

        txtPrevEndDate.setEditable(false);
        txtPrevEndDate.setPreferredSize(new java.awt.Dimension(100, 20));
        
        endDatesPanel.add(txtPrevEndDate);

        jLabel3.setText("Date fin r\u00e9elle");
        endDatesPanel.add(jLabel3);

        txtRealEndDate.setEditable(false);
        txtRealEndDate.setPreferredSize(new java.awt.Dimension(100, 20));
        endDatesPanel.add(txtRealEndDate);

        contentPanel.add(endDatesPanel);

        durationPanel.setLayout(new java.awt.GridLayout(1, 4, 2, 2));

        durationPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        jLabel15.setText("Dur\u00e9e pr\u00e9visionnelle");
        durationPanel.add(jLabel15);

        txtPrevDuration.setEditable(false);
        txtPrevDuration.setPreferredSize(new java.awt.Dimension(100, 20));
        durationPanel.add(txtPrevDuration);

        jLabel14.setText("Dur\u00e9e r\u00e9elle");
        durationPanel.add(jLabel14);

        txtRealDuration.setEditable(false);
        txtRealDuration.setPreferredSize(new java.awt.Dimension(100, 20));
        durationPanel.add(txtRealDuration);

        contentPanel.add(durationPanel);

        startOffsetPanel.setLayout(new java.awt.GridLayout(1, 3, 2, 2));

        startOffsetPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        jLabel5.setText("D\u00e9calage de d\u00e9but");
        startOffsetPanel.add(jLabel5);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        txtStartOffset.setEditable(false);
        txtStartOffset.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(txtStartOffset);

        jLabel6.setText("jours");
        jPanel2.add(jLabel6);

        startOffsetPanel.add(jPanel2);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        txtStartOffset2.setEditable(false);
        txtStartOffset2.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel7.add(txtStartOffset2);

        jLabel7.setText("%");
        jPanel7.add(jLabel7);

        startOffsetPanel.add(jPanel7);

        contentPanel.add(startOffsetPanel);

        endOffsetPanel.setLayout(new java.awt.GridLayout(1, 3, 2, 2));

        endOffsetPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        jLabel11.setText("D\u00e9calage de fin");
        endOffsetPanel.add(jLabel11);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        txtGlobalOffset.setEditable(false);
        txtGlobalOffset.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel10.add(txtGlobalOffset);

        jLabel12.setText("jours");
        jPanel10.add(jLabel12);

        endOffsetPanel.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        txtGlobalOffset2.setEditable(false);
        txtGlobalOffset2.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel11.add(txtGlobalOffset2);

        jLabel13.setText("%");
        jPanel11.add(jLabel13);

        endOffsetPanel.add(jPanel11);

        contentPanel.add(endOffsetPanel);

        durationOffsetPanel.setLayout(new java.awt.GridLayout(1, 3, 2, 2));

        durationOffsetPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        jLabel8.setText("D\u00e9calage de dur\u00e9e");
        durationOffsetPanel.add(jLabel8);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        txtDurationOffset.setEditable(false);
        txtDurationOffset.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel8.add(txtDurationOffset);

        jLabel9.setText("jours");
        jPanel8.add(jLabel9);

        durationOffsetPanel.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        txtDurationOffset2.setEditable(false);
        txtDurationOffset2.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel9.add(txtDurationOffset2);

        jLabel10.setText("%");
        jPanel9.add(jLabel10);

        durationOffsetPanel.add(jPanel9);

        contentPanel.add(durationOffsetPanel);

        daysChartPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.add(daysChartPanel);

        jSeparator1.setBorder(new javax.swing.border.CompoundBorder());
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        contentPanel.add(jSeparator1);

        workPanel.setLayout(new java.awt.GridLayout(1, 4, 2, 2));

        workPanel.setMaximumSize(new java.awt.Dimension(32767, 20));
        jLabel16.setText("Charges pr\u00e9visionnelles");
        workPanel.add(jLabel16);

        txtPrevWorkAmount.setEditable(false);
        txtPrevWorkAmount.setPreferredSize(new java.awt.Dimension(100, 20));
        workPanel.add(txtPrevWorkAmount);

        jLabel17.setText("Charges r\u00e9elles");
        workPanel.add(jLabel17);

        txtRealWorkAmount.setEditable(false);
        txtRealWorkAmount.setPreferredSize(new java.awt.Dimension(100, 20));
        workPanel.add(txtRealWorkAmount);

        contentPanel.add(workPanel);

        workChartPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.add(workChartPanel);

        jPanel1.add(contentPanel, java.awt.BorderLayout.CENTER);

        bResUsg.setText("Resource usage...");
        bResUsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bResUsgMouseClicked(evt);
            }
        });

        buttonsPanel.add(bResUsg);

        jPanel1.add(buttonsPanel, java.awt.BorderLayout.SOUTH);

    }
    
    
    
    
    
	private void bResUsgMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	
	
	
	private void updateTextFields() 
	{
		if(plannableC.getName() != null)
		{
			txtTitle.setText(plannableC.getName());
		}
		else
		{			
			txtTitle.setText("n/a");
		}
		
		if(plannableC.getPrevStartDate() != null)
		{
			txtPrevStartDate.setText(Utils.dateToString(plannableC.getPrevStartDate()));
		}
		else
		{			
			txtPrevStartDate.setText("n/a");
		}
		
		if(plannableC.getPrevEndDate() != null)
		{
			txtPrevEndDate.setText(Utils.dateToString(plannableC.getPrevEndDate()));
		}
		else
		{			
			txtPrevEndDate.setText("n/a");
		}
		
		if(plannableC.getRealStartDate() != null)
		{
			txtRealStartDate.setText(Utils.dateToString(plannableC.getRealStartDate()));
		}
		else
		{			
			txtRealStartDate.setText("n/a");
		}
		
		if(plannableC.getRealEndDate() != null)
		{
			txtRealEndDate.setText(Utils.dateToString(plannableC.getRealEndDate()));
		}
		else
		{			
			txtRealEndDate.setText("n/a");
		}
		
		if(plannableC.getPrevDuration() != null)
		{
			txtPrevDuration.setText(plannableC.getPrevDuration().toString());
		}
		else
		{			
			txtPrevDuration.setText("n/a");
		}
		
		if(plannableC.getRealDuration() != null)
		{
			txtRealDuration.setText(plannableC.getRealDuration().toString());		
		}
		else
		{			
			txtRealDuration.setText("n/a");
		}
		
		if(plannableC.getStartOffset() != null)
		{
			txtStartOffset.setText(plannableC.getStartOffset().toString());
		}
		else
		{			
			txtStartOffset.setText("n/a");
		}
		
		if(plannableC.getDurationOffset() != null)
		{
			txtDurationOffset.setText(plannableC.getDurationOffset().toString());
		}
		else
		{			
			txtDurationOffset.setText("n/a");
		}
		
		if(plannableC.getGlobalOffset() != null)
		{
			txtGlobalOffset.setText(plannableC.getGlobalOffset().toString());		
		}
		else
		{			
			txtGlobalOffset.setText("n/a");
		}
		
		if(plannableC.getStartOffsetPrct() != null)
		{
			txtStartOffset2.setText(Utils.doubleToString(plannableC.getStartOffsetPrct()));
		}
		else
		{			
			txtStartOffset2.setText("n/a");
		}		
		
		if(plannableC.getDurationOffsetPrct() != null)
		{
			txtDurationOffset2.setText(Utils.doubleToString(plannableC.getDurationOffsetPrct()));
		}
		else
		{			
			txtDurationOffset2.setText("n/a");
		}
		
		if(plannableC.getGlobalOffsetPrct() != null)
		{
			txtGlobalOffset2.setText(Utils.doubleToString(plannableC.getGlobalOffsetPrct()));
		}
		else
		{			
			txtGlobalOffset2.setText("n/a");
		}
				
		if(plannableC.getPrevWorkAmount() != null)
		{
			txtPrevWorkAmount.setText(plannableC.getPrevWorkAmount().toString());
		}
		else
		{			
			txtPrevWorkAmount.setText("n/a");
		}
		
		if(plannableC.getRealWorkAmount() != null)
		{
			txtRealWorkAmount.setText(plannableC.getRealWorkAmount().toString());
		}
		else
		{			
			txtRealWorkAmount.setText("n/a");
		}
	}	
	
	
		
		
		
	private void updateDaysChart() 
	{
		TaskSeriesCollection dataset = new TaskSeriesCollection();
		TaskSeries tsR = new TaskSeries("Realization");
		TaskSeries tsP = new TaskSeries("Prevision");
		try {
			tsP.add(new Task("", new SimpleTimePeriod(plannableC
					.getPrevStartDate(), plannableC.getPrevEndDate())));
			tsR.add(new Task("", new SimpleTimePeriod(plannableC
					.getRealStartDate(), plannableC.getRealEndDate())));

		} catch (Exception e) {
			assert true;
		}
		dataset.add(tsP);
		dataset.add(tsR);
		JFreeChart chart = ChartFactory.createGanttChart("", "", "Dates",
				dataset, true, false, false);
		daysChartPanel.add( new ChartPanel(chart));
	}
	
	
	
	
	private void updateWorkChart() 
	{
		// row keys...
        String series1 = "First";
        
        // column keys...
        String category1 = "Prévision";
        String category2 = "Réalisation";
        
        // create the dataset...
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.addValue(plannableC.getPrevWorkAmount(), series1, category1);
        dataset.addValue(plannableC.getRealWorkAmount(), series1, category2);
        
		JFreeChart chart = ChartFactory.createBarChart3D("Charges",
                "",
                "",
                dataset,
                PlotOrientation.VERTICAL,
                true, // show legend
                true,
                true
               );
		workChartPanel.add( new ChartPanel(chart));
	}
	
	

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		JFrame f = new JFrame();
		WorkBreakDownElement wbe1 = null;
		try {
			wbe1 = new WorkBreakDownElement("wbe1",
					"Mettre en place le projet", Utils
							.stringToDate("01-09-2005"), Utils
							.stringToDate("20-09-2005"), new Double(15), Utils
							.stringToDate("05-09-2005"), Utils
							.stringToDate("15-09-2005"), new Double(16));
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}

		f.getContentPane().add(new ViewPlannable(new ControlPlannable(wbe1)));
		f.setVisible(true);
	}

}
